# Copyright 2024-2026 Nexa AI, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

[versions]
aiNexaCore = "0.0.22"
agp = "8.12.1"
kotlin = "2.2.0"
coreKtx = "1.10.1"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
lifecycleRuntimeKtx = "2.6.1"
activityCompose = "1.8.0"
composeBom = "2024.09.00"
kotlinx-serialization ="1.6.3"
okhttp = "5.1.0"
appcompat = "1.6.1"
material = "1.10.0"
kotlinxCoroutinesAndroid = "1.7.3"
constraintlayout = "2.1.4"
aws-android-s3 = '2.81.0'
autoSize = "v1.2.1"
immBar = "3.2.2"
activity = "1.11.0"
toaster = "13.8"
recyclerview = "1.3.1"
gson = "2.10.1"
glide = "5.0.5"
activityVersion = "1.12.2"
markwon = "4.6.2"

[libraries]
glide = {group = "com.github.bumptech.glide", name = "glide", version.ref = "glide"}
gson = {group = "com.google.code.gson", name = "gson", version.ref = "gson"}
recyclerview = {group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview"}
toaster = {group = "com.github.getActivity", name = "Toaster", version.ref = "toaster"}
imm-bar-ktx = {group = "com.geyifeng.immersionbar", name = "immersionbar-ktx", version.ref = "immBar"}
imm-bar = {group = "com.geyifeng.immersionbar", name = "immersionbar", version.ref = "immBar"}
auto-size = {group = "com.github.JessYanCoding", name = "AndroidAutoSize", version.ref = "autoSize"}
aws-android-sdk-s3 = {group = "com.amazonaws", name = "aws-android-sdk-s3", version.ref = "aws-android-s3"}
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
okhttp = { group = "com.squareup.okhttp3", name="okhttp", version.ref = "okhttp" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutinesAndroid" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
ai-nexa-core = {group = "ai.nexa", name = "core", version.ref = "aiNexaCore"}
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activityVersion" }
markwon-core = { group = "io.noties.markwon", name = "core", version.ref = "markwon" }
markwon-strikethrough = { group = "io.noties.markwon", name = "ext-strikethrough", version.ref = "markwon" }
markwon-tables = { group = "io.noties.markwon", name = "ext-tables", version.ref = "markwon" }
markwon-linkify = { group = "io.noties.markwon", name = "linkify", version.ref = "markwon" }
markwon-latex = { group = "io.noties.markwon", name = "ext-latex", version.ref = "markwon" }
markwon-inline-parser = { group = "io.noties.markwon", name = "inline-parser", version.ref = "markwon" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }

